# Generated by Django 4.2.3 on 2023-07-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='authorUser',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='commentPost',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='commentUser',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='dateCreation',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='dateCreation',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='postCategory',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='category',
            new_name='categoryThrough',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='post',
            new_name='postThrough',
        ),
        migrations.RemoveField(
            model_name='author',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
        migrations.AddField(
            model_name='author',
            name='ratingAuthor',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='categoryType',
            field=models.CharField(choices=[('AR', 'Статья'), ('NW', 'Новость')], default='AR', max_length=2),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
